# Generated by Django 2.2.5 on 2019-10-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_dashboard',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
