# Generated by Django 2.2.5 on 2019-10-30 06:16

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191025_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_dashboard',
            field=djongo.models.fields.DictField(default={}),
        ),
    ]
